name: Test LLVM Fortran compilers, check which flags are needed to force the automatic arrays on the heap

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:


jobs:

  test:
    name: Run LLVM Flang tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-15-intel]
        compiler: [armflang, amdflang, flang]  # Compilers to test
        flag: [mmlir, fno-stack-arrays]  # Optimization flags to test
        exclude:
          - os: ubuntu-latest
            compiler: armflang
          - os: ubuntu-24.04-arm
            compiler: amdflang
          - os: macos-latest
            compiler: armflang
          - os: macos-latest
            compiler: amdflang
          - os: macos-15-intel
            compiler: armflang
          - os: macos-15-intel
            compiler: amdflang
          - os: windows-latest
            compiler: armflang
          - os: windows-latest
            compiler: amdflang
          - os: windows-11-arm
            compiler: armflang
          - os: windows-11-arm
            compiler: amdflang


    steps:

      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Install Arm Toolchain for Linux
        if: matrix.compiler == 'armflang'
        run: bash ./install_atfl

      - name: Install AMD AOMP Flang
        if: matrix.compiler == 'amdflang'
        run: bash install_aomp 20 600  # Retry up to 20 times with a delay of 600 seconds between retries, to avoid transient network issues.

      - name: Install LLVM Flang
        shell: bash
        if: matrix.compiler == 'flang'
        run: bash ./install_llvm

      - name: Install gdb and git
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update || true && sudo apt install -y gdb git
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update || true && brew install gdb git
          else
            choco install -y git  # gdb cannot be installed using choco
          fi

      - name: Conduct the test
        shell: bash
        run: |
          bash ./flang_heap_arrays ${{ matrix.compiler }} ${{ matrix.flag }}
